services:
  # Base image containing dependencies.
  base:
    image: droneworkspace:base
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: base    
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: True
    environment:
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
      - /dev/ttyUSB0:/dev/ttyUSB0
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0

  # Overlay Container
  overlay:
    extends: base
    image: droneworkspace:overlay
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: overlay

  # Developer container
  dev:
    extends: overlay
    image: droneworkspace:dev
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USERNAME=${USERNAME:-devuser}
    volumes:
      - ./firmware:/firmware:rw
      - ./src:/DroneWorkspace:rw
      # VSCode settings for container development
      - ./vscodesettings:/DroneWorkspace/.vscode:rw
    ports:
      # Forward port for running QGC locally
      - 14570:14570
    user: ${USERNAME:-devuser}
    command: sleep infinity
